### ISSUE TITLE
The `ctype_alpha` function could be avoid.

### ISSUE THREAD

**Issue by Alexandre-T** [longitude-one/wkt-parser#8]
Replace the `ctype_alpha` function: 
https://github.com/longitude-one/wkt-parser/blob/546dfadfc11f467739aec39d329d7fd5271b69eb/lib/LongitudeOne/Geo/WKT/Lexer.php#L107

Remove the ctype requirement in composer:
https://github.com/longitude-one/wkt-parser/blob/9acf4e9bf564e68da1126cc529981ef09ade0bd4/composer.json#L28

**Comment by kcassam** [comment]
```
if (ctype_alpha($value)) {
```
can be replaced by 
 
```
if (preg_match('/^[a-zA-Z]+$/', $value)) {
```

but it is less readable.

Why do you want to remove the ctype requirement in composer ?

**Comment by Alexandre-T** [comment]
Thank you for the regexp!
Since this is a library for other libraries, I'd like to minimize its dependencies. That's why I excluded the quality tools from the main composer.json file. While it's not a critical issue, it does help keep the footprint small.

**Comment by Alexandre-T** [comment]
Fixed by @kcassam  in https://github.com/longitude-one/wkt-parser/pull/15 .
Thank you
